### ISSUE TITLE
配方錯誤／重複

### ISSUE THREAD

**Issue by EvanHsieh0415** [xiaoliziawa/New-Create#11]
- [ ] `create_dd:crafting/diamond_shard_compacting` / `minecraft:kjs/diamond`
  ![圖片](https://github.com/xiaoliziawa/New-Create/assets/74277414/a7971a8e-2479-4145-b51e-cb39a1478307)
- [ ] `create_dd:crafting/bronze_ingot_from_compacting` / `minecraft:kjs/create_dd_bronze_ingot_3`
  ![圖片](https://github.com/xiaoliziawa/New-Create/assets/74277414/1ae3e1d6-ca8b-4336-844c-d08a77869c32)

**Comment by Qi-Month** [comment]
钻石这种的回头删一个
