### ISSUE TITLE
部分平衡性配方问题

### ISSUE THREAD

**Issue by WX4M** [xiaoliziawa/New-Create#13]
1.所有矿石只能用粉碎轮处理粗矿，无增产（原版机动是有概率产生的），但仅有锡可以用石磨研磨粗矿进行增产，不知是否有意为之？
2.本包主线内推荐的，需要功夫制作，成本也较高的铸铁做成的套装属性价比不足。
拿铸铁胸甲为例，其属性为+6护甲，耐久为200点。
而本包能够制作的铜、锌胸甲皆有与之相同的护甲值，但耐久值为240、320点，
相比之下，铸铁的性价比太低了。（虽然锌是进度靠后的，但铜可是最泛滥的资源）
3.特大矿团簇是本包添加的吗？这东西我好评
![QQ图片20240530215919](https://github.com/xiaoliziawa/New-Create/assets/60736971/9a407bbd-a9ac-4c00-a8df-8c2d4548d1f3)

**Comment by Qi-Month** [comment]
好的,晚点我做一下调整

**Comment by WX4M** [comment]
新增了沙子的鼓风机清洗配方但没有清除老配方，导致尘土不会产生
