### ISSUE TITLE
深板岩鵝卵石在篝火中燒製成石頭而不是深板岩

### ISSUE THREAD

**Issue by EvanHsieh0415** [xiaoliziawa/New-Create#6]
![圖片](https://github.com/xiaoliziawa/New-Create/assets/74277414/07aff6a1-50a3-47f9-8e50-cee78273551f)

刻意為之？

**Comment by Qi-Month** [comment]
否，input填的是tag，所以...芒果大佬有什么解决思路吗

**Comment by EvanHsieh0415** [comment]
深板岩鵝卵石![圖片](https://github.com/xiaoliziawa/New-Create/assets/74277414/c5c3e810-915f-4522-985e-df1b48542174)
鵝卵石![圖片](https://github.com/xiaoliziawa/New-Create/assets/74277414/8c6bec70-a620-4b40-81ff-b2e4a0a6895a)

**Comment by Qi-Month** [comment]
![image](https://github.com/xiaoliziawa/New-Create/assets/115912382/49edb1fe-3d38-4aa5-813e-897e93554659)
Fix
