### ISSUE TITLE
Functional Storage 未打補丁

### ISSUE THREAD

**Issue by EvanHsieh0415** [xiaoliziawa/New-Create#7]
![圖片](https://github.com/xiaoliziawa/New-Create/assets/74277414/da08811e-9f95-4725-b182-c7bb23c1a7c2)

**Comment by Qi-Month** [comment]
补丁又是什么()

**Comment by Qi-Month** [comment]
![image](https://github.com/xiaoliziawa/New-Create/assets/115912382/1b3698e5-9e24-429b-9950-49799803d050)
Fix
