### ISSUE TITLE
陶瓷防腐液桶與防腐液桶配方不一致

### ISSUE THREAD

**Issue by EvanHsieh0415** [xiaoliziawa/New-Create#9]
![圖片](https://github.com/xiaoliziawa/New-Create/assets/74277414/251324d2-290e-4e0e-9cce-f8adcb36959b)
![圖片](https://github.com/xiaoliziawa/New-Create/assets/74277414/499eafe1-5122-4666-b055-c519cab926bc)

**Comment by Qi-Month** [comment]
呜誒(´◑д◐｀)

**Comment by Qi-Month** [comment]
![image](https://github.com/xiaoliziawa/New-Create/assets/115912382/45963ad0-76b8-4af0-ae7e-b1ede2e25a4d)
修复惹
